[project]
name = "tanaab-mmm"
version = "0.1.0"
description = "Automated Tibanna gas mining platform"
readme = "README.md"
requires-python = ">=3.13"

[tool.poetry]
package-mode = false

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.poetry.dependencies]
lean = "^1.0.220"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
ruff = "^0.12.7"
pre-commit = "^4.2.0"
quantconnect-stubs = "^17232"
